baseURL = "https://www.markut.net/"
languageCode = "tr-tr"
title = "Markut Dergi"
theme = "Markut"
#10 şubat 2020
timeout= 120000
pygmentsUseClassic = false
relativeURLs = true
paginatePath = "sayfa"
paginate = 8
[caches]
[caches.getjson]
[caches.getCSV]
dir = ":cacheDir/:project"
maxAge = "1m"

[permalinks]
  blog = "/blog/:slug/"
[taxonomies]
  author = "yazar"
  tag = "tags"
[params]
description ="Markut, endüstriyel tasarım dergisidir. Endüstri tasarımı bağlamında genel tasarım disiplinleriyle de ilişkili olarak içerikler üreten online dergidir."


areklamimg = "/img/markut-dergimizin-parcasi.jpg"
areklamurl = "/reklam-sponsorluk/"
areklamtitle = "Bu Alana Reklam Verin!"
areklamdesc = "Dergimize reklam vermek ister misiniz? Aylık binlerce okuyucuya sahip olduğumuz dergide; ürününüzü, içeriğinizi, firmanızı, sitenizi, yarışmanızı tanıtabilirsiniz. Unutmayın ki, nitelikli yazılarımızdan oluşan dergi, nitelikli insanlar tarfından okunmaktadır. A reklam alanına en uygun fiyatla şimdi reklam verebilirsiniz."

breklamimg = "/img/markut-b-reklam-gorsel.jpg"
breklamurl = "/reklam-sponsorluk/"
breklamtitle = "Bu Alana Reklam Verin!"
breklamdesc = "Dergimize reklam vermek ister misiniz? Aylık binlerce okuyucuya sahip olduğumuz dergide; ürününüzü, içeriğinizi, firmanızı, sitenizi, yarışmanızı tanıtabilirsiniz. Unutmayın ki; nitelikli yazılarımızdan oluşan dergi, nitelikli insanlar tarfından okunmaktadır. B reklam alanına en uygun fiyatla şimdi reklam verebilirsiniz."

creklamimg = "/img/markut-twitter-hesabi-yayinda.png"
creklamurl = "https://twitter.com/markutworks"
creklamtitle = "Twitter Hesabımız Yayında!"
creklamdesc = "Bir platform iki kuş. Twitter'da yerimizi aldık. Takip etmek ister misiniz? Bibirinden faydalı içerikleri kaçırmamak için Twitter adresimizi takip edebilirsiniz."
creklamrenk = "#ff2f0021"

d1reklamimg = "/img/galeyan-dergi-reklam.jpg"
d1reklamurl = "https://www.galeyandergi.com/"
d1reklamtitle = "Kültür Sanat Dergisi Okuyun!"
d1reklamdesc = "Galeyan -yaygın yanlış kullanımının aksine- halkın gerçeğe, sanata ve doğruya yürüyeceği yolu göstermek ve bu yolda yürümesi için onu ısıtmak, kaynatmak ve coşturmak gayeleriyle sanat, edebiyat, tiyatro, resim, müzik, sosyal hayat, felsefe, siyaset ve bilim alanlarında yayın yapmak amacıyla kurulmuş bir yayın organıdır."

d2reklamimg = "/img/reklam-markut-thumbnail.jpg"
d2reklamurl = "/reklam-sponsorluk/"
d2reklamtitle = "Bu Alana Reklam Verin!"
d2reklamdesc = "Dergimize reklam vermek ister misiniz? Aylık binlerce okuyucuya sahip olduğumuz dergide; ürününüzü, içeriğinizi, firmanızı, sitenizi, yarışmanızı tanıtabilirsiniz. Unutmayın ki; nitelikli yazılarımızdan oluşan dergi, nitelikli insanlar tarfından okunmaktadır. D2 reklam alanına en uygun fiyatla şimdi reklam verebilirsiniz."


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = true
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]