baseURL = "https://www.markut.net/"
languageCode = "tr-tr"
title = "Markut"
theme = "Markut"
#10 şubat 2020

[caches]
[caches.getjson]
[caches.getCSV]
dir = ":cacheDir/:project"
maxAge = "1m"

[permalinks]
  blog = "/blog/:slug/"
[taxonomies]
  author = "yazar"
  tag = "tags"
[params]
description ="Markut, endüstriyel tasarım dergisidir. Endüstri tasarımı bağlamında genel tasarım disiplinleriyle de ilişkili olarak içerikler üreten online dergidir."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true