baseURL = "https://www.markut.net/"
languageCode = "tr-tr"
title = "Markut Dergi"
theme = "Markut"
#10 şubat 2020
timeout= 120000
pygmentsUseClassic = false
relativeURLs = true
paginatePath = "sayfa"
paginate = 8
[caches]
[caches.getjson]
[caches.getCSV]
dir = ":cacheDir/:project"
maxAge = "1m"

[permalinks]
  blog = "/blog/:slug/"
[taxonomies]
  author = "yazar"
  tag = "tags"
[params]
description ="Markut, endüstriyel tasarım dergisidir. Endüstri tasarımı bağlamında genel tasarım disiplinleriyle de ilişkili olarak içerikler üreten online dergidir."


areklamimg = "/img/markut-dergimizin-parcasi.jpg"
areklamurl = "/reklam-sponsorluk/"
areklamtitle = "Dergimizin Bir Parçası Olun"
areklamdesc = "Dergimize reklam vererek yapbozu tamamlayan parça olabilirsiniz. Sizin eksik parçanız tanıtım ise biz tamamlayacağız. A reklam alanına şimdi reklam verebilirsiniz."

breklamimg = "/img/markut-b-reklam-gorsel.jpg"
breklamurl = "/reklam-sponsorluk/"
breklamtitle = "Dergimize Sponsor Olun"
breklamdesc = "Dergimize reklam vererek ürününüzü, içeriğinizi öne çıkarabilirsiniz. B reklam alanına şimdi reklam verebilirsiniz."

creklamimg = "/img/markut-twitter-hesabi-yayinda.png"
creklamurl = "https://twitter.com/markutworks"
creklamtitle = "Twitter Hesabımız Yayında!"
creklamdesc = "Bir platform iki kuş. Twitter'da yerimizi aldık. Takip etmek ister misiniz? Bibirinden faydalı içerikleri kaçırmamak için Twitter adresimizi takip edebilirsiniz."
creklamrenk = "#ff2f0021"

d1reklamimg = "/img/markut-dergimizin-parcasi.jpg"
d1reklamurl = "/reklam-sponsorluk/"
d1reklamtitle = "Dergimizin Bir Parçası Olun"
d1reklamdesc = "Dergimize reklam vererek ürününüzü, içeriğinizi öne çıkarabilirsiniz. D1 reklam alanına şimdi reklam verebilirsiniz."

d2reklamimg = "/img/reklam-markut-thumbnail.jpg"
d2reklamurl = "/reklam-sponsorluk/"
d2reklamtitle = "MARKUT'un Yanında Uçun"
d2reklamdesc = "Dergimize reklam vererek ürününüzü, içeriğinizi öne çıkarabilirsiniz. D2 reklam alanına şimdi reklam verebilirsiniz."


[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = true
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]