baseURL = "https://www.markut.net/"
languageCode = "tr-tr"
title = "Markut"
theme = "Markut"
#10 şubat 2020
timeout= 60000
pygmentsUseClassic = false
relativeURLs = true
[caches]
[caches.getjson]
[caches.getCSV]
dir = ":cacheDir/:project"
maxAge = "1m"

[permalinks]
  blog = "/blog/:slug/"
[taxonomies]
  author = "yazar"
  tag = "tags"
[params]
description ="Markut, endüstriyel tasarım dergisidir. Endüstri tasarımı bağlamında genel tasarım disiplinleriyle de ilişkili olarak içerikler üreten online dergidir."
areklampc = "/img/a-sponsor.png"
areklamph = "/img/a-rsponsor.png"

breklampc = "/img/b-sponsor.png"
breklamph = "/img/b-rsponsor.png"

creklampc = "/img/c-sponsor.png"
creklamph = "/img/c-rsponsor.png"

d1reklamph = "/img/d-rsponsor.png"

d2reklamph = "/img/d-rsponsor.png"

d3reklamph ="/img/d-rsponsor.png"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.asciidocExt]
    backend = "html5"
    extensions = []
    failureLevel = "fatal"
    noHeaderOrFooter = true
    safeMode = "unsafe"
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = ""
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = true
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2