---
new_page_extension: html
auto_deploy: false
admin_path: editor
webhook_url: 
sections:
- type: directory
  path: content/dergi
  label: Dergi İçerikleri
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Sayfalar
  create: all
  match: "*"
- type: directory
  path: content/yazar
  label: Yazarlar
  create: all
  match: "**/*"
- type: directory
  path: content/tags
  label: Tags
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: content
public_path: ''
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.54.0
